routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resources([
    'projects' => 'ProjectController'
]);
// Route::get('/project', 'ProjectController@index');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'nama', 'tanggal_mulai', 'tanggal_target'
    ];
}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|max:255',
            'tanggal_mulai' => 'required',
            'tanggal_target' => 'required'
        ]);

        Project::create([
            'nama' => $request['nama'],
            'tanggal_mulai' => $request['tanggal_mulai'],
            'tanggal_target' => $request['tanggal_target'],
            'created_at' => now(),
        ]);

        return redirect()->route('projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        // $project = Project::find($project);
        // dd($project);
        return view('projects.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        $request->validate([
            'nama' => 'required|max:255',
            'tanggal_mulai' => 'required',
            'tanggal_target' => 'required'
        ]);

        $project->update($request->all());
        $project->updated_at = now();
        $project->save();
        return redirect()->route('projects.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $project->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/app.blade.php
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <title>{{ config('app.name', 'Laravel') }}</title>
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body class="py-4">
        <div class="container">
            <h1>@yield('pagetitle')</h1>
            @yield('content')
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('pagetitle')
    Create Project
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form class="col-md-6" action="{{ route('projects.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="nama">Project Title</label>
            <input type="text" class="form-control" name="nama" placeholder="Project Title" value="{{ old('nama') }}" required>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="tanggal_mulai">Start Date</label>
                <input type="date" class="form-control" name="tanggal_mulai" value="{{ old('tanggal_mulai') }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="tanggal_target">Finished target</label>
                <input type="date" class="form-control" name="tanggal_target" value="{{ old('tanggal_target') }}" required>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('pagetitle')
    Edit - {{ $project['nama'] }}
@endsection

@section('content')
    <form class="col-md-6" action="{{ route('projects.update', $project['id']) }}" method="POST">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="nama">Project Title</label>
            <input type="text" class="form-control" name="nama" placeholder="Project Title" value="{{ old('nama') ?: $project['nama'] }}" required>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="tanggal_mulai">Start Date</label>
                <input type="date" class="form-control" name="tanggal_mulai" value="{{ old('tanggal_mulai') ?: $project['tanggal_mulai'] }}" required>
            </div>
            <div class="form-group col-md-6">
                <label for="tanggal_target">Finished target</label>
                <input type="date" class="form-control" name="tanggal_target" value="{{ old('tanggal_target') ?: $project['tanggal_target'] }}" required>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('pagetitle')
    Projects
@endsection

@section('content')
    <a href="{{ route('projects.create') }}" class="btn btn-primary my-3">Create New Project</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Project Name</th>
                <th scope="col">Start Date</th>
                <th scope="col">Finished Target</th>
                <th scope="col">Finished Date</th>
                <th scope="col" colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($projects as $project)
            <tr>
                <th scope="row">{{ $loop->iteration }}</th>
                <td>{{ $project['nama'] }}</td>
                <td>{{ $project['tanggal_mulai'] }}</td>
                <td>{{ $project['tanggal_target'] }}</td>
                @if(is_null($project['tanggal_selesai']))
                <td>-</td>
                @else
                <td>{{ $project['tanggal_selesai'] }}</td>
                @endif
                <td>
                    <a href="{{ route('projects.show', $project['id']) }}" class="btn btn-outline-primary">Show</a>
                    <a href="{{ route('projects.edit', $project['id']) }}" class="btn btn-outline-secondary">Edit</a>
                    <form action="{{ route('projects.destroy', $project['id']) }}" method="POST">
                        <input type="submit" value="Delete" class="btn btn-outline-secondary">
                        @method('delete')
                        @csrf
                    </form>
                    {{-- <a href="{{ route('projects.destroy', $project['id']) }}" class="btn btn-outline-secondary">Destroy</a> --}}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endsection